version: '3'
services:

  nginx:
    build: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/src:/usr/share/nginx/html
    environment:
      - HOST_IP=${HOST_IP}
    networks:
      - pipkp

  discovery_service:
    build: discovery_server
    ports:
      - "8082:8082"
    environment:
      - HOST_IP=${HOST_IP}
    networks:
      - pipkp

  demo:
    container_name: demo
    build: demo
    ports:
      - "8085:8085"
    environment:
      - HOST_IP=${HOST_IP}
    networks:
      - pipkp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST_IP}:8080/hello"]
      interval: 10s
      timeout: 10s
      retries: 10

  demo_data:
    container_name: demo_spring_data
    build: demo
    ports:
      - "8085:8085"
    environment:
      - HOST_IP=${HOST_IP}
    networks:
      - pipkp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST_IP}:8080/hello"]
      interval: 10s
      timeout: 10s
      retries: 10


  java_service:
    build: java_service
    ports:
      - "8087:8087"
    environment:
      - HOST_IP=${HOST_IP}
    networks:
      - pipkp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST_IP}:8080/java"]
      interval: 10s
      timeout: 10s
      retries: 10

networks:
  pipkp:
    driver: bridge
