version: '3'
services:

  nginx:
    build: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/src:/usr/share/nginx/html
    environment:
      - HOST_IP=${HOST_IP}
    networks:
      - pipkp

  discovery_service:
    build: discovery_server
    ports:
      - "8082:8082"
    environment:
      - HOST_IP=${HOST_IP}
    networks:
      - pipkp

  demo:
    container_name: demo
    build: demo
    ports:
      - "8088:8088"
    environment:
      - HOST_IP=${HOST_IP}
    networks:
      - pipkp

  demo_data:
    container_name: demospringdata
    build: demo_spring_data
    ports:
      - "8087:8087"
    environment:
      - HOST_IP=${HOST_IP}
    networks:
      - pipkp


networks:
  pipkp:
    driver: bridge
